version: "3.9"

services:

  postgres:
    image: pgvector/pgvector:pg16
    container_name: sentinel_postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7
    container_name: sentinel_redis
    ports:
      - "6379:6379"

  fastapi:
    build: .
    container_name: sentinel_api
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app

  celery_worker:
    build: .
    container_name: sentinel_worker
    depends_on:
      - redis
      - postgres
    command: celery -A worker.celery_app.celery_app worker --loglevel=info --concurrency=2
    volumes:
      - .:/app
    env_file:
      - .env

volumes:
  postgres_data: